### Il backup si gestisce tramite plugin esterni
### Tolerations e nodeSelector vanno applicati sulle risorse oppure tramite patch oppure tramite una struttura kustomization + overlay
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
  enableSuperuserAccess: false
  instances: 1
#  affinity:
#    enablePodAntiAffinity: true
#    topologyKey: kubernetes.io/hostname
#    podAntiAffinityType: required
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 18
  storage:
    size: 1Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-db
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: keycloak-db
  podMetricsEndpoints:
  - port: metrics
