apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: envoy-gateway
  namespace: fleet-local
spec:
  repo: https://github.com/LolloLomb/fleet-lab.git
  branch: main
  paths:
    - envoy-gateway