#tolerations:
#  - key: node/gaia
#    operator: Equal
#    value: "true"
#    effect: NoSchedule
#nodeSelector:
#  node-type: baremetal
auth:
  enabled: true
  usersExistingSecret: valkey-auth
  aclUsers:
    default:
      permissions: "~* &* +@all"
      passwordKey: password
replica:
  enabled: true
  replicas: 2
  replicationUser: default
  persistence:
    size: 1Gi

