### Il backup si gestisce tramite plugin esterni
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  tolerations:
    - key: node/gaia
      operator: Equal
      value: "true"
      effect: NoSchedule
  nodeSelector:
    node-type: baremetal
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
  enableSuperuserAccess: false
  instances: 1
#  affinity:
#    enablePodAntiAffinity: true
#    topologyKey: kubernetes.io/hostname
#    podAntiAffinityType: required
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  storage:
    size: 1Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: keycloak-db
  podMetricsEndpoints:
  - port: metrics
