metrics:
  enabled: true
postgres:
  enabled: false
database:
  type: "postgres"
  host: "keycloak-db-rw.keycloak.svc.cluster.local"
  existingSecret: "keycloak-db-credentials"
  secretKeys:
    passwordKey: "password"
    usernameKey: "username"
tolerations:
  - key: node/gaia
    operator: Equal
    value: "true"
    effect: NoSchedule
nodeSelector:
  node-type: baremetal
